name: wakatime-stats

on:
    schedule:
        - cron: "30 16 * * *"
    workflow_dispatch:

jobs:
    update-readme:
        name: Update Readme with Metrics
        runs-on: ubuntu-latest
        steps:
            - uses: anmol098/waka-readme-stats@master
              with:
                  COMMIT_BY_ME: "True"
                  COMMIT_MESSAGE: "Updated dev metrics"
                  COMMIT_USERNAME: "vcsil"
                  COMMIT_EMAIL: "vcsilva@poli.ufrj.br"
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
                  SHOW_OS: "False"
                  SHOW_PROJECTS: "True"
                  SHOW_PROFILE_VIEWS: "False"
                  SHOW_EDITORS: "False"
                  SHOW_LANGUAGE: "True"
                  SHOW_LANGUAGE_PER_REPO: "False"
                  SHOW_LINES_OF_CODE: "True"
                  SHOW_COMMIT: "True"
                  SHOW_LOC_CHART: "True"
                  SHOW_DAYS_OF_WEEK: "True"
                  SHOW_SHORT_INFO: "True"
