name: Update recent github activity

on:
    schedule:
        - cron: "* 6 * * *"
    workflow_dispatch:

jobs:
    recent-activity:
        name: "Update README with latest activity"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Repository"
              uses: actions/Checkout@v3
            - name: "Update README.md from TEMPLATE.md"
              uses: Readme-Workflows/recent-activity@main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  CONFIG_FILE: "./.github/recent-activity.config.yml"
